# This is the very first notebook demonstrating tensor operations 

### Tensors are the basic data object on which Pytorch operates

Pytorch is the open source Machine Learning library used to develop deep neural networks and other machine learning tasks 

- as_tensor
- ceil_
- reshape
- stack
- resize

In [1]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.as_tensor()

Helps in creating tensor 

In [8]:
# Example 1 - working (change this)
arr = np.array([[1,2,3],[3,4,5]])
new_arr = torch.as_tensor(arr)
new_arr

tensor([[1, 2, 3],
        [3, 4, 5]])

Here we created a tensor from a numpy array , and this tensor will share the memory space with the numpy array that means any change in numpy array leads to change in tensor array also implicitly 

In [9]:
arr[0][1] = 100
arr

array([[  1, 100,   3],
       [  3,   4,   5]])

In [10]:
new_arr

tensor([[  1, 100,   3],
        [  3,   4,   5]])

But this property fails when one change the data type of the new tensor created 

In [12]:
arr = np.array([[1,2,3],[3,4,5]])
new_arr = torch.as_tensor(arr, dtype=torch.float)
new_arr

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [13]:
arr[0][1] = 100
arr

array([[  1, 100,   3],
       [  3,   4,   5]])

In [14]:
new_arr

tensor([[1., 2., 3.],
        [3., 4., 5.]])

The new_arr is value is not changed as the data type of the tensor was changed when creating tensor

## Function 2 - ceil_()

Does element wise ceil operation inplace

In [15]:
arr = torch.tensor([[1.2,2.3,6.7],[7.8,6.0,9.4]])
arr

tensor([[1.2000, 2.3000, 6.7000],
        [7.8000, 6.0000, 9.4000]])

In [16]:
arr.ceil_()
arr

tensor([[ 2.,  3.,  7.],
        [ 8.,  6., 10.]])

Element wise ceil operation performed on tensor created

In [17]:
arr1 = torch.tensor([[2.2,1.7],[7.8,6.0]])
arr1

tensor([[2.2000, 1.7000],
        [7.8000, 6.0000]])

In [18]:
arr1.ceil_()
arr1

tensor([[3., 2.],
        [8., 6.]])

In [21]:

arr3 = torch.as_tensor([[2.2,1.7],[7.8,6.0]])
arr3

tensor([[2.2000, 1.7000],
        [7.8000, 6.0000]])

## Function 3 - reshape()

Helps in reshaping a tensor

In [22]:
arr = torch.tensor([[1.2,2.3,6.7],[7.8,6.0,9.4]])
arr.shape

torch.Size([2, 3])

In [24]:
arr = arr.reshape((1,1,6))
print(arr.shape)
arr

torch.Size([1, 1, 6])


tensor([[[1.2000, 2.3000, 6.7000, 7.8000, 6.0000, 9.4000]]])

Reshape the tensor 

In [25]:
arr = torch.tensor([[1.2,2.3],[7.8,6.0]])
arr.shape


torch.Size([2, 2])

In [26]:
arr = arr.reshape((4,1,1))
print(arr.shape)
arr

torch.Size([4, 1, 1])


tensor([[[1.2000]],

        [[2.3000]],

        [[7.8000]],

        [[6.0000]]])

In [27]:
arr = torch.tensor([[1.2,2.3],[7.8,6.0]])
arr.shape

torch.Size([2, 2])

In [28]:
arr = arr.reshape((1,1))
print(arr.shape)
arr

RuntimeError: shape '[1, 1]' is invalid for input of size 4

The shape should be equal to the size of the original tensor

## Function 4 - stack()

Helps adding 2 or more tensors with a new dimension

In [30]:
# Example 1
arr1 = torch.tensor([[1,2],[3,4]])
arr2 = torch.tensor([[5,6],[7,8]])
arr1.shape, arr2.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [33]:
arr3 = torch.stack((arr1,arr2),dim=0)
print(arr3.shape)
arr3

torch.Size([2, 2, 2])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

stacks two tensors along dim=0

In [35]:
# Example 2
arr4 = torch.stack((arr1,arr2),dim=1)
print(arr4.shape)
arr4

torch.Size([2, 2, 2])


tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

Stacking of two tensors along dim=1

In [37]:
# Example 3
arr1 = torch.tensor([[1,2,0],[3,4,5]])
arr2 = torch.tensor([[5,6],[7,8]])
arr1.shape, arr2.shape

(torch.Size([2, 3]), torch.Size([2, 2]))

In [38]:
arr5 = torch.stack((arr1,arr2),dim=0)
print(arr5.shape)
arr5

RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [2, 2] at entry 1

Both the tensors which needs to be stacked should be of equal dimension

## Function 5 - resize_()

Helps in resizing a tensor of desired size 

In [39]:
# Example 1 
arr1 = torch.tensor([[1,2,0],[3,4,5]])
arr1.shape

torch.Size([2, 3])

In [43]:
arr1.resize_(2,2)
print(arr1.shape)
arr1

torch.Size([2, 2])


tensor([[1, 2],
        [0, 3]])

In [53]:
# Example 2 --- For large dimension it will not break else pick random values and insert into it 
arr1.resize_(3,6)
print(arr1.shape)
arr1

torch.Size([3, 6])


tensor([[                  1,                   2,                   0,
                           3,                   4,                   5],
        [3486411945030215268, 3690474702589276465, 3180166294196008756,
         8104636957536251170, 7162263158163907173, 8462656716707034229],
        [7311068618034541413, 2466321603649696626, 7017771692297694773,
         3616445623364117876, 6068655667629010224, 3617017437963826481]])

In [50]:
# Example 3 - breaking (to illustrate when it breaks)

arr1 = torch.tensor([[1,2,0],[3,4,5]])
arr1.shape

torch.Size([2, 3])

In [52]:
arr1.resize_()


TypeError: resize_() missing 1 required positional arguments: "size"

You need to give a specific size 

## Conclusion

So we covered 5 functions that can be performed on tensors, next we will look onto more advanced implementation via tensors

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [54]:
!pip install jovian --upgrade --quiet

In [55]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
